// 全站双语文案（展示层）。所有页面组件只从这里取文字，避免中英混排与硬编码。
//
// 术语沿革（2026-09-10 起的既有裁定必须保留）：
// - 「未记录」/「Not recorded」是缺失值的唯一写法，不得回落到 0 或空白。
// - 「策略级（workspace-only）」「事后补录」「AI 均分」「暂无阶段评估」「未找到页面」
//   「均分」等字符串被 e2e 断言直接引用，改动需同步更新 website/scripts/e2e-smoke.mjs。
// - `suspected`（越界尝试但未取得内容）不作外显标注，因此这里没有对应文案。
import type { Locale } from './catalog';

const zh = {
  // ---- 站点与导航 ----
  skip: '跳到主要内容',
  brandSubtitle: '模型评测档案',
  navLabel: '主导航',
  search: '搜索',
  searchOpen: '打开全站搜索',
  language: 'English',
  languageLabel: '切换到英文',
  repository: 'GitHub 仓库',
  themeLabel: '配色',
  menu: '菜单',
  close: '关闭',

  // ---- 通用 ----
  all: '全部',
  allTasks: '全部任务',
  allModels: '全部模型',
  allPhases: '全部阶段',
  allRuns: '全部运行',
  allWorks: '全部作品',
  view: '查看档案',
  viewTask: '查看任务',
  viewAllTasks: '查看全部任务',
  viewRecord: '查看档案记录',
  viewSource: '查看源码',
  viewFullPrompt: '展开完整需求',
  viewLessPrompt: '收起需求',
  openStandalone: '独立打开',
  openFullscreen: '全屏查看',
  openNewWindow: '新窗口打开',
  reload: '重新加载',
  downloadSvg: '下载 SVG',
  share: '复制分享链接',
  copied: '链接已复制',
  source: '来源',
  sourceReport: '原始报告',
  notRecorded: '未记录',
  results: '项结果',
  total: '合计',
  perTask: '逐任务记录',
  batchStats: '批次统计',
  archive: '归档版本',
  archiveCommit: '归档提交',
  phaseDetail: '阶段详情',
  modelDetail: '模型详情',
  cost: '费用',
  runs: '运行',
  tasks: '任务',
  models: '模型',
  phases: '阶段',
  artifacts: '成果',
  duration: '累计用时',
  tokens: 'Token 过路量',
  filters: '检索与筛选',

  // ---- 首页 ----
  heroTitle: 'An archive of things\nAI models actually made.',
  heroTitleZh: '记录模型真正创造出来的东西。',
  heroIntro: '在相同的题目下，比较不同模型的真实作品、运行证据与独立评价。',
  browseTasks: '浏览任务',
  compareWorks: '对比作品',
  archiveSummary: '归档概况',
  archiveProgress: '档案进度',
  archiveProgressNote: '已归档任务 / 各阶段计划题数',
  stats: '档案统计',
  progressModels: '模型',
  progressPhases: '阶段',
  progressRuns: '运行',
  progressTasks: '任务',
  featured: '精选作品',
  featuredKicker: 'FEATURED WORKS',
  currentExhibition: '当前展览',
  exhibitionKicker: 'CURRENT EXHIBITION',
  modelsInArchive: '档案中的模型',
  modelsKicker: 'MODELS IN ARCHIVE',
  recentlyArchived: '最新归档',
  recentlyKicker: 'RECENTLY ARCHIVED',
  methodologyTeaser: '方法简介',
  methodologyTeaserKicker: 'METHODOLOGY',
  readMethodology: '阅读评测方法',
  archiveSignal: '已测试 / 计划',
  wallCaption: 'AI CREATIVITY IN THE OPEN',
  wallNote: '相同题目 · 真实输出 · 独立评价 · 可验证记录',
  wallNoteSecondary: '同一个题目，不同模型的创作解释。',

  // ---- 任务档案 ----
  taskArchive: '任务档案',
  taskArchiveKicker: 'TASK ARCHIVE',
  archivedRunsLabel: '条已归档运行',
  searchPlaceholder: '搜索任务标题、Prompt 或模型',
  searchLabel: '搜索任务',
  filterType: '类型',
  filterModel: '模型',
  filterPhase: '阶段',
  typeOther: '其他',
  runsSuffix: '个运行',
  runsArchivedSuffix: '条归档运行',
  noResults: '没有符合条件的任务。',
  taskCategory: '任务类别',
  prompt: '原始需求',
  originalPrompt: '原始需求',
  promptKicker: 'ORIGINAL PROMPT',
  promptInput: '逐字输入',
  translation: '中文译文',
  expected: '理论成果',
  verification: '后补验收建议',
  threeInterpretations: '同一题目的三种模型解释',
  interpretationsKicker: 'THREE INTERPRETATIONS',
  comparisonMetrics: '执行对比',
  metricsKicker: 'COMPARISON METRICS',
  runRecords: '运行档案',
  runRecordsKicker: 'RUN RECORDS',
  relatedTasks: '相关任务',
  relatedKicker: 'RELATED TASKS',
  notArchivedYet: '尚未归档',
  notArchivedNote: '该模型尚未在这道题上完成归档运行。',
  interpretationsNote: '三个结果使用同样的宽度、同样的预览比例，不标注「最佳模型」。',

  // ---- 运行档案 ----
  runRecord: '运行档案',
  runRecordKicker: 'RUN RECORD',
  runId: 'RUN ID',
  recorded: '归档时间',
  runtime: '运行时间',
  apiCalls: 'API 调用',
  toolCalls: '工具调用',
  retries: '重试次数',
  harness: 'Harness',
  session: '会话',
  snapshot: '运行快照',
  snapshots: '模型快照（harness 报告的 model id）',
  snapshotNote: '本次运行实际使用的模型快照；同一模型的不同快照不构成同一配置。',
  snapshotCurrent: '当前',
  snapshotRetired: '已退役',
  archiveRecord: '档案记录',
  archiveRecordKicker: 'ARCHIVE RECORD',
  technicalRecord: '技术记录',
  technicalRecordNote: '会话、提交、快照、隔离与环境信息默认折叠。',
  isolation: '隔离等级',
  contamination: '越界判定',
  environment: '运行环境',
  continuation: '补充轮',
  followupInput: '补充轮输入（逐字）',
  audit: '收尾审查',
  auditReport: '审查报告',
  sessionLogHash: '会话日志哈希',
  postHoc: '事后补录',
  telemetryHidden: '工具调用不可见 · 默认视为遵守规则',
  telemetryNote: '该模型 / harness 不提供中间工具调用记录，收尾审查无法覆盖路径、命令、仓库查询等维度；按既定规则默认视为遵守规则，不影响成绩。',
  configuration: '执行配置',
  config: '执行配置',
  sourceEvidence: '来源证据',
  sourceEvidenceKicker: 'SOURCE EVIDENCE',
  reviews: '评价与证据',
  criticalNotes: '评审记录',
  criticalNotesKicker: 'CRITICAL NOTES',
  independentEvaluations: '独立评价',
  human: '人工评价',
  humanReview: '人工评价',
  ai: 'AI 评价',
  aiReview: 'AI 评价',
  reviewKickerHuman: 'HUMAN REVIEW',
  reviewKickerAi: 'AI REVIEW',
  noReviews: '本运行暂无独立评价：人工评价与 AI 评价均未产出。',
  disclaimer: '引用结论，不代表网站独立复验',
  translationNote: '原文为中文，未提供英译',
  translatedNote: '英文为译文',
  artworkSection: '展示',
  recordSection: '运行记录',
  environmentSection: '运行环境',
  previewNote: '预览说明',
  loadPreview: '加载交互预览',
  artworkUnavailable: '作品无法加载',
  artworkUnavailableNote: '归档成果未能加载，可直接查看来源文件。',
  runNav: '本节导航',
  positionLabel: '作品位次',
  taskVersionLabel: '题目版本',
  artifactType: '类型',
  artifactEntry: '入口文件',
  promptSource: '需求来源',
  noRunYet: '该题暂无归档运行。',

  // ---- 模型 ----
  modelArchive: '模型档案',
  modelArchiveKicker: 'MODEL ARCHIVE',
  selectedWorks: '精选作品',
  selectedWorksKicker: 'SELECTED WORKS',
  archiveStatistics: '档案统计',
  archiveStatsKicker: 'ARCHIVE STATISTICS',
  allWorksKicker: 'ALL WORKS',
  runHistory: '运行历史',
  runHistoryKicker: 'RUN HISTORY',
  phaseProgress: '阶段进度',
  phaseProgressKicker: 'PHASE PROGRESS',
  archivedWorksSuffix: '件归档作品',
  batch: '批次',
  assessment: '阶段评估',
  aiAverage: 'AI 均分',
  noAssessment: '暂无阶段评估',
  averageNotePrefix: '本模型有',
  averageNoteSuffix: '份 AI 阶段评估，简单均分 {avg}/100。各评委口径不同，逐份评分、口径与免责声明并列在下方；均分只作概览，不得据此排序或做跨模型排行榜。',
  modelWorks: '作品',
  worksSuffix: '件作品',
  provider: '提供方',
  versionNote: '版本口径',

  // ---- 阶段 ----
  phaseIndexKicker: 'PHASE INDEX',
  exhibitionSeason: '展览季',
  phaseKicker: 'PHASE',
  plannedTasksNote: '计划题数说明',
  completed: '已完成',
  inProgress: '进行中',
  taskVersions: '已归档题目版本',

  // ---- 对比 ----
  compareTitle: '同题作品对比',
  compareKicker: 'SIDE BY SIDE',
  compareIntro: '选择同一任务版本下的两条运行。选择会写入 URL，可直接分享和刷新恢复。',
  selectTask: '选择任务',
  leftRun: '左侧作品',
  rightRun: '右侧作品',
  sideOne: '作品 A',
  sideTwo: '作品 B',
  unavailable: '当前任务只有一条真实运行记录，尚无第二项可比较。',
  invalid: '无效或不匹配的选择已被忽略。',
  noRight: '请选择右侧运行以开始对比',
  crossModel: '跨模型比较需注明 harness、预算与隔离差异。',
  compareHint: '同一任务版本下的两次运行可并排比较。',
  executionComparison: '执行对比',
  evaluationComparison: '评价对比',
  openRunRecord: '打开运行档案',
  noReview: '尚无评价',
  metricRow: '指标',
  modelSelector: '模型选择器',

  // ---- 方法 ----
  methodology: '评测方法与边界',
  methodologyKicker: 'PROVENANCE FIRST',
  methodologyIntro: '本网站呈现可追溯的归档记录，不把缺失值解释为零，也不把不同口径的数字压成排行榜。',
  methodologyLead: '这里保存的不是「谁更强」的结论，而是一批可被复核的作品与运行记录：相同题目、真实输出、独立评价、可验证来源。',
  principleSame: '相同题目',
  principleSameBody: '同一阶段的模型收到完全相同的题目文本与资源限制；题目版本递增而不是覆盖原文，比较只在同一题目版本内进行。',
  principleReal: '真实输出',
  principleRealBody: '页面上展示的是模型实际交付的文件：网页可以被打开、SVG 可以被查看、运行记录保留调用与重试次数。',
  principleIndependent: '独立评价',
  principleIndependentBody: '人工评价、各版 AI 评价与本次展示站验证分别记录，口径与免责声明随分数并列展示，不静默合并。',
  principleNoRanking: '不做综合排名',
  principleNoRankingBody: '不同评委、不同口径的分数不合成排行榜；缺失值显示「未记录」，不推断单题费用或模型能力。',
  principleProvenance: '来源优先',
  principleProvenanceBody: '每条题目、指标与评价都保留文件路径、行定位与归档提交，公开链接固定到具体提交，可逐条复核。',
  historicalTitle: '历史结论如何展示',
  historicalBody: '每条阶段评估都标注来源与口径：DeepSeek 的 93.6/100 引自历史 AI 报告；Muse Spark 的 84.9/100 来自维护 agent 的非盲评 v1。两者口径不同，不可直接比较，也不作为网站独立证明。任务 06、07 的人工观感与 AI 评估存在分歧，两种判断在运行详情中并列保留。',
  boundariesTitle: '边界与隔离',
  boundariesBody: '档案中的隔离与越界信息按归档原文显示：策略级约束能防手滑、可被事后审查，但不构成强制隔离，展示站也不会把它写成「已审计」。',

  // ---- 状态与错误 ----
  statusArchived: '已归档',
  statusVerified: '已验证',
  statusPartial: '部分完成',
  statusPending: '待归档',
  statusFailed: '失败',
  notFound: '未找到页面',
  notFoundNote: '链接中的标识不存在，或这条记录尚未进入公开索引。',
  notFoundBack: '返回概览',
  errorLoad: '作品无法加载',

  // ---- 命令面板 ----
  searchTitle: '搜索 VibeTest',
  searchPlaceholderFull: '搜索任务、模型或运行…',
  searchHint: '输入关键词；↑ ↓ 选择，Enter 打开',
  searchEmpty: '没有匹配的档案记录。',
  searchTaskGroup: '任务',
  searchModelGroup: '模型',
  searchRunGroup: '运行',
  searchPromptGroup: '题目',
  searchClose: '关闭搜索',
  searchResults: '搜索结果',

  // ---- 页脚 ----
  footerContact: '联系方式',
  footerLinks: '站点链接',
  footerMethodology: '评测方法',
  footerData: '档案数据',
  footerPersonal: '个人网站',
  footerTagline: '相同题目 · 真实输出 · 独立评价',
  footerStance: '忠实引用归档来源，不生成综合排名。',
  footerNote: 'ARCHIVE 001 / 2026 · 模型评测档案',
};

export type Labels = Record<keyof typeof zh, string>;

const en: Labels = {
  skip: 'Skip to content',
  brandSubtitle: 'Model Evaluation Archive',
  navLabel: 'Primary navigation',
  search: 'Search',
  searchOpen: 'Open site search',
  language: '中文',
  languageLabel: 'Switch to Chinese',
  repository: 'GitHub repository',
  themeLabel: 'Palette',
  menu: 'Menu',
  close: 'Close',

  all: 'All',
  allTasks: 'All tasks',
  allModels: 'All models',
  allPhases: 'All phases',
  allRuns: 'All runs',
  allWorks: 'All works',
  view: 'View record',
  viewTask: 'View task',
  viewAllTasks: 'View all tasks',
  viewRecord: 'View archive record',
  viewSource: 'View source',
  viewFullPrompt: 'Show full prompt',
  viewLessPrompt: 'Hide prompt',
  openStandalone: 'Open independent copy',
  openFullscreen: 'Open fullscreen',
  openNewWindow: 'Open in a new window',
  reload: 'Reload',
  downloadSvg: 'Download SVG',
  share: 'Copy share link',
  copied: 'Link copied',
  source: 'Source',
  sourceReport: 'Source report',
  notRecorded: 'Not recorded',
  results: 'results',
  total: 'Total',
  perTask: 'Per-task records',
  batchStats: 'Batch metrics',
  archive: 'Archive version',
  archiveCommit: 'Archive commit',
  phaseDetail: 'Phase details',
  modelDetail: 'Model details',
  cost: 'Cost',
  runs: 'Runs',
  tasks: 'Tasks',
  models: 'Models',
  phases: 'Phases',
  artifacts: 'Artifacts',
  duration: 'Total duration',
  tokens: 'Token throughput',
  filters: 'Search and filters',

  heroTitle: 'An archive of things\nAI models actually made.',
  heroTitleZh: 'Records of what the models actually made.',
  heroIntro: 'On the same task set, compare what each model actually made, how the run went, and what independent reviewers concluded.',
  browseTasks: 'Browse tasks',
  compareWorks: 'Compare works',
  archiveSummary: 'Archive summary',
  archiveProgress: 'Archive progress',
  archiveProgressNote: 'Archived tasks / tasks planned per phase',
  stats: 'Archive statistics',
  progressModels: 'Models',
  progressPhases: 'Phases',
  progressRuns: 'Runs',
  progressTasks: 'Tasks',
  featured: 'Featured works',
  featuredKicker: 'FEATURED WORKS',
  currentExhibition: 'Current exhibition',
  exhibitionKicker: 'CURRENT EXHIBITION',
  modelsInArchive: 'Models in archive',
  modelsKicker: 'MODELS IN ARCHIVE',
  recentlyArchived: 'Recently archived',
  recentlyKicker: 'RECENTLY ARCHIVED',
  methodologyTeaser: 'Methodology',
  methodologyTeaserKicker: 'METHODOLOGY',
  readMethodology: 'Read the methodology',
  archiveSignal: 'Tested / planned',
  wallCaption: 'AI CREATIVITY IN THE OPEN',
  wallNote: 'Same prompts · Real outputs · Independent reviews · Verifiable evidence',
  wallNoteSecondary: 'One task, several interpretations.',

  taskArchive: 'Task archive',
  taskArchiveKicker: 'TASK ARCHIVE',
  archivedRunsLabel: 'archived runs',
  searchPlaceholder: 'Search task title, prompt or model',
  searchLabel: 'Search tasks',
  filterType: 'Type',
  filterModel: 'Model',
  filterPhase: 'Phase',
  typeOther: 'Other',
  runsSuffix: 'runs',
  runsArchivedSuffix: 'archived runs',
  noResults: 'No tasks match these filters.',
  taskCategory: 'Task category',
  prompt: 'Original prompt',
  originalPrompt: 'Original prompt',
  promptKicker: 'ORIGINAL PROMPT',
  promptInput: 'Verbatim input',
  translation: 'Chinese translation',
  expected: 'Expected outcome',
  verification: 'Additional verification guidance',
  threeInterpretations: 'Same task, three model interpretations',
  interpretationsKicker: 'THREE INTERPRETATIONS',
  comparisonMetrics: 'Comparison metrics',
  metricsKicker: 'COMPARISON METRICS',
  runRecords: 'Run records',
  runRecordsKicker: 'RUN RECORDS',
  relatedTasks: 'Related tasks',
  relatedKicker: 'RELATED TASKS',
  notArchivedYet: 'Not archived yet',
  notArchivedNote: 'This model has not completed this task in Archive 001.',
  interpretationsNote: 'All three results use the same width and the same preview ratio; no model is marked as best.',

  runRecord: 'Archive record',
  runRecordKicker: 'RUN RECORD',
  runId: 'RUN ID',
  recorded: 'Recorded',
  runtime: 'Runtime',
  apiCalls: 'API calls',
  toolCalls: 'Tool calls',
  retries: 'Retries',
  harness: 'Harness',
  session: 'Session',
  snapshot: 'Run snapshot',
  snapshots: 'Model snapshots (harness-reported model id)',
  snapshotNote: 'The model snapshot this run actually used; different snapshots of one model are not the same configuration.',
  snapshotCurrent: 'Current',
  snapshotRetired: 'Retired',
  archiveRecord: 'Archive record',
  archiveRecordKicker: 'ARCHIVE RECORD',
  technicalRecord: 'Technical record',
  technicalRecordNote: 'Session, commit, snapshot, isolation and environment details stay collapsed by default.',
  isolation: 'Isolation level',
  contamination: 'Boundary check',
  environment: 'Environment',
  continuation: 'Continuation turns',
  followupInput: 'Continuation input (verbatim)',
  audit: 'Completion audit',
  auditReport: 'Audit report',
  sessionLogHash: 'Session log hash',
  postHoc: 'post-hoc reconstruction',
  telemetryHidden: 'Tool calls not exposed · assumed compliant',
  telemetryNote: 'This model or harness does not expose intermediate tool calls, so the closing audit cannot cover paths, commands or repository queries; per the standing rule the run is assumed compliant and its scores are unaffected.',
  configuration: 'Execution configuration',
  config: 'Execution configuration',
  sourceEvidence: 'Source evidence',
  sourceEvidenceKicker: 'SOURCE EVIDENCE',
  reviews: 'Reviews and evidence',
  criticalNotes: 'Independent evaluations',
  criticalNotesKicker: 'CRITICAL NOTES',
  independentEvaluations: 'Independent evaluations',
  human: 'Human review',
  humanReview: 'Human review',
  ai: 'AI review',
  aiReview: 'AI review',
  reviewKickerHuman: 'HUMAN REVIEW',
  reviewKickerAi: 'AI REVIEW',
  noReviews: 'No independent reviews are archived for this run yet: neither human nor AI review has been produced.',
  disclaimer: 'Quoted conclusion; not independently reverified by this website',
  translationNote: 'Original text is Chinese; no English translation provided',
  translatedNote: 'English is a translation',
  artworkSection: 'Artwork',
  recordSection: 'Records',
  environmentSection: 'Technical',
  previewNote: 'Preview note',
  loadPreview: 'Load interactive preview',
  artworkUnavailable: 'Artwork unavailable',
  artworkUnavailableNote: 'The archived artifact could not be loaded. The source file is still available.',
  runNav: 'On this record',
  positionLabel: 'Position',
  taskVersionLabel: 'Task version',
  artifactType: 'Type',
  artifactEntry: 'Entry file',
  promptSource: 'Prompt source',
  noRunYet: 'No archived run for this task yet.',

  modelArchive: 'Model archive',
  modelArchiveKicker: 'MODEL ARCHIVE',
  selectedWorks: 'Selected works',
  selectedWorksKicker: 'SELECTED WORKS',
  archiveStatistics: 'Archive statistics',
  archiveStatsKicker: 'ARCHIVE STATISTICS',
  allWorksKicker: 'ALL WORKS',
  runHistory: 'Run history',
  runHistoryKicker: 'RUN HISTORY',
  phaseProgress: 'Phase progress',
  phaseProgressKicker: 'PHASE PROGRESS',
  archivedWorksSuffix: 'archived works',
  batch: 'Batch',
  assessment: 'Phase assessment',
  aiAverage: 'AI average',
  noAssessment: 'No phase assessment',
  averageNotePrefix: 'This model has',
  averageNoteSuffix: 'AI phase assessments, simple average {avg}/100. The rubrics differ, so every score, method and disclaimer is kept side by side below; the average is an overview only and must not be turned into a ranking.',
  modelWorks: 'Works',
  worksSuffix: 'works',
  provider: 'Provider',
  versionNote: 'Version basis',

  phaseIndexKicker: 'PHASE INDEX',
  exhibitionSeason: 'Exhibition season',
  phaseKicker: 'PHASE',
  plannedTasksNote: 'How the planned task count is sourced',
  completed: 'Completed',
  inProgress: 'In progress',
  taskVersions: 'Archived task versions',

  compareTitle: 'Compare works on one task',
  compareKicker: 'SIDE BY SIDE',
  compareIntro: 'Choose two runs of the same task version. The selection is written into the URL so it can be shared and restored after a refresh.',
  selectTask: 'Select task',
  leftRun: 'Left work',
  rightRun: 'Right work',
  sideOne: 'Work A',
  sideTwo: 'Work B',
  unavailable: 'Only one real run exists for this task, so there is no second result to compare yet.',
  invalid: 'Invalid or mismatched selections were ignored.',
  noRight: 'Select a right-hand run to start comparing',
  crossModel: 'Cross-model comparison must note differences in harness, budget and isolation.',
  compareHint: 'Two runs of the same task version can be compared side by side.',
  executionComparison: 'Execution comparison',
  evaluationComparison: 'Evaluation comparison',
  openRunRecord: 'Open run record',
  noReview: 'No review archived',
  metricRow: 'Metric',
  modelSelector: 'Model selectors',

  methodology: 'Methodology and boundaries',
  methodologyKicker: 'PROVENANCE FIRST',
  methodologyIntro: 'This site presents traceable archive records. Missing values are not zero, and incompatible measurements are not collapsed into a leaderboard.',
  methodologyLead: 'What is kept here is not a claim about which model is strongest, but a set of works and run records that can be checked: same prompts, real outputs, independent reviews, verifiable sources.',
  principleSame: 'Same prompts',
  principleSameBody: 'Models in one phase receive exactly the same prompt text and resource limits. Prompt versions increase instead of overwriting the original, and comparison stays within one task version.',
  principleReal: 'Real outputs',
  principleRealBody: 'Pages show the files the models actually delivered: pages can be opened, SVGs can be inspected, and run records keep the call and retry counts.',
  principleIndependent: 'Independent reviews',
  principleIndependentBody: 'Human reviews, each AI review version and this website\u2019s own checks are recorded separately; scores are shown side by side with their method and disclaimer, never silently merged.',
  principleNoRanking: 'No aggregate ranking',
  principleNoRankingBody: 'Scores from different reviewers and rubrics are never merged into a leaderboard; unknown values stay "Not recorded" instead of being inferred.',
  principleProvenance: 'Provenance first',
  principleProvenanceBody: 'Every prompt, metric and review keeps its file path, line location and archive commit, and public links are pinned to that commit so each claim can be re-checked.',
  historicalTitle: 'How historical conclusions are presented',
  historicalBody: 'Every phase assessment carries its source and method: the DeepSeek 93.6/100 is quoted from a historical AI report, while the Muse Spark 84.9/100 comes from the maintenance agent non-blind v1 review. The two use different rubrics and must not be compared directly; neither is an independent proof by this website. For tasks 06 and 07 the human judgment differs from the AI assessment, so both are retained side by side.',
  boundariesTitle: 'Boundaries and isolation',
  boundariesBody: 'Isolation and boundary information is shown as archived: a policy-level constraint discourages mistakes and can be reviewed afterwards, but it is not enforced isolation, and this site will not call it "audited".',

  statusArchived: 'Archived',
  statusVerified: 'Verified',
  statusPartial: 'Partial',
  statusPending: 'Pending',
  statusFailed: 'Failed',
  notFound: 'Page not found',
  notFoundNote: 'The identifier does not exist or is not included in the public index.',
  notFoundBack: 'Back to overview',
  errorLoad: 'Artwork unavailable',

  searchTitle: 'Search VibeTest',
  searchPlaceholderFull: 'Search tasks, models or runs…',
  searchHint: 'Type to search; ↑ ↓ to choose, Enter to open',
  searchEmpty: 'No matching archive records.',
  searchTaskGroup: 'Task',
  searchModelGroup: 'Model',
  searchRunGroup: 'Run',
  searchPromptGroup: 'Prompt',
  searchClose: 'Close search',
  searchResults: 'Search results',

  footerContact: 'Contact',
  footerLinks: 'Site links',
  footerMethodology: 'Methodology',
  footerData: 'Archive data',
  footerPersonal: 'Personal website',
  footerTagline: 'Same prompts. Real outputs. Independent reviews.',
  footerStance: 'Source-faithful archive. No synthetic leaderboard.',
  footerNote: 'ARCHIVE 001 / 2026 · Model Evaluation Archive',
};

export const labelsFor = (locale: Locale): Labels => (locale === 'zh' ? zh : en);

/** 任务类别名：中英双语，列表页筛选与卡片共用。 */
export const categoryNames: Record<string, { zh: string; en: string }> = {
  website: { zh: '网站', en: 'Website' },
  'svg-illustration': { zh: 'SVG 插画', en: 'SVG illustration' },
  'svg-clock': { zh: 'SVG 时钟', en: 'SVG clock' },
  game: { zh: '游戏', en: 'Game' },
  'creative-tool': { zh: '创作工具', en: 'Creative tool' },
  'productivity-tool': { zh: '效率工具', en: 'Productivity tool' },
  utility: { zh: '实用工具', en: 'Utility' },
  'data-dashboard': { zh: '数据仪表盘', en: 'Data dashboard' },
  simulation: { zh: '交互模拟', en: 'Interactive simulation' },
  'engineering-tool': { zh: '工程工具', en: 'Engineering tool' },
};

export const categoryName = (category: string, locale: Locale) => categoryNames[category]?.[locale] ?? category;

export const isolationLabels: Record<string, { zh: string; en: string }> = {
  'workspace-only': { zh: '策略级（workspace-only）', en: 'Policy-level (workspace-only)' },
  'os-user-isolation': { zh: '独立用户隔离', en: 'Separate OS user' },
  container: { zh: '容器隔离', en: 'Container' },
  unknown: { zh: '未记录', en: 'Not recorded' },
};

export const contaminationLabels: Record<string, { zh: string; en: string }> = {
  clean: { zh: '未发现越界（已声明范围内通过检查）', en: 'No boundary violation observed (passed within declared scope)' },
  // `suspected`（越界尝试但未取得内容）不作外显标注，因此这里没有对应文案：
  // 该状态只记入审计档案，运行页不显示（2026-09-10 组织者决定，见 docs/audit-method.md 第 5 节）。
  contaminated: { zh: '已确认获取外部答案（标注）', en: 'Confirmed access to external answers (flagged)' },
  unknown: { zh: '未判定', en: 'Not assessed' },
};

/** 指标名与批次表标签：中英双语，两种语言共用一套调用点。 */
export const metricLabels = (locale: Locale) => (locale === 'zh' ? {
  duration: '累计用时', api: 'API 调用', tools: '工具调用', failures: '失败 / 重试',
  inputTokens: '输入 token', outputTokens: '输出 token', cacheRead: '缓存读 token', totalTokens: '总 token 过路量',
  tasks: '任务数', sessions: '会话数', noRight: '请选择右侧运行以开始对比',
} : {
  duration: 'Total duration', api: 'API calls', tools: 'Tool calls', failures: 'Failures / retries',
  inputTokens: 'Input tokens', outputTokens: 'Output tokens', cacheRead: 'Cache read', totalTokens: 'Total tokens',
  tasks: 'Tasks', sessions: 'Sessions', noRight: 'Select a right-hand run to start comparing',
});

/** `3 个运行` / `3 runs`：数字与量词分开拼，避免中文空格问题。 */
export const runsCount = (locale: Locale, count: number) => (locale === 'zh'
  ? `${count} 个运行`
  : `${count} ${count === 1 ? 'run' : 'runs'}`);
